'use client';

import { motion } from 'framer-motion';
import { RotateCcw, Save, Download, Settings } from 'lucide-react';
import { useChatStore } from '~/stores/chat';
import { useNotificationStore } from '../ui/NotificationContainer';

export function SessionControls() {
  const { currentScenario, messages, startNewSession } = useChatStore();
  const { addNotification } = useNotificationStore();

  const handleNewSession = () => {
    startNewSession();
    addNotification({
      type: 'success',
      title: 'New Session Started',
      message: 'Previous conversation cleared. Ready for a fresh start!',
    });
  };

  const handleSaveSession = () => {
    // TODO: Implement session saving to Supabase
    addNotification({
      type: 'info',
      title: 'Session Saved',
      message: 'Your conversation has been saved for later review.',
    });
  };

  const handleExportSession = () => {
    if (!currentScenario || messages.length === 0) {
      addNotification({
        type: 'error',
        title: 'Export Failed',
        message: 'There is no session data to export.',
      });
      return;
    }
    
    // Format the conversation as readable text
    const timestamp = new Date().toLocaleString();
    let textContent = `DigiConvo Chat Session\n`;
    textContent += `Scenario: ${currentScenario.title}\n`;
    textContent += `Date: ${timestamp}\n`;
    textContent += `\n${'='.repeat(50)}\n\n`;
    
    messages.forEach((message, index) => {
      const sender = message.sender === 'user' ? 'You' : currentScenario.title;
      textContent += `${sender}: ${message.content}\n\n`;
    });
    
    textContent += `${'='.repeat(50)}\n`;
    textContent += `End of Session - Generated by DigiConvo`;
    
    const blob = new Blob([textContent], {
      type: 'text/plain',
    });
    
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `digiconvo-session-${new Date().getTime()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    addNotification({
      type: 'success',
      title: 'Session Exported',
      message: 'Your conversation data has been downloaded.',
    });
  };

  if (!currentScenario) return null;

  return (
    <div className="flex items-center gap-2">
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={handleNewSession}
        className="p-2 theme-text-secondary theme-text-hover theme-hover rounded-lg transition-colors cursor-pointer"
        title="Start new session"
      >
        <RotateCcw className="w-4 h-4" />
      </motion.button>
      
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={handleSaveSession}
        className="p-2 theme-text-secondary theme-text-hover theme-hover rounded-lg transition-colors cursor-pointer"
        title="Save session"
        disabled={messages.length === 0}
      >
        <Save className="w-4 h-4" />
      </motion.button>
      
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={handleExportSession}
        className="p-2 theme-text-secondary theme-text-hover theme-hover rounded-lg transition-colors cursor-pointer"
        title="Export session"
        disabled={messages.length === 0}
      >
        <Download className="w-4 h-4" />
      </motion.button>
      
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        className="p-2 theme-text-secondary theme-text-hover theme-hover rounded-lg transition-colors cursor-pointer"
        title="Settings"
      >
        <Settings className="w-4 h-4" />
      </motion.button>
    </div>
  );
}
